// CSV values come from experiments/fusion/study/e4_reranking.json.
// Each point selects the largest vs_best_fusion_arm across four models, on 200 queries.
// Run from qdrant-landing with node content/documentation/headless/reranker/gain/generate.mjs.
import {readFileSync, writeFileSync, mkdirSync} from 'node:fs';
import {csvParse} from 'd3-dsv';
import {drawing} from './plot.mjs';
const folder = 'content/documentation/headless/reranker/gain';
const rows = csvParse(readFileSync(`${folder}/data.csv`, 'utf8'));
const palette = JSON.parse(readFileSync('data/viz.json', 'utf8')).palette.categorical;
const names = [...new Set(rows.map(row => row.dataset))];
const series = names.map((name, i) => ({name, color: palette[i], values: rows.filter(row => row.dataset === name).map(row => Number(row.best_gain))}));
mkdirSync('static/documentation/reranker', {recursive:true});
writeFileSync('static/documentation/reranker/gain.svg', drawing(series, 760, true));
const columns = rows.columns;
writeFileSync(`${folder}/data.md`, '\n**Measured reranker results**\n\n| ' + columns.join(' | ') + ' |\n|' + columns.map(() => ' --- |').join('') + '\n' + rows.map(row => '| ' + columns.map(col => row[col]).join(' | ') + ' |').join('\n') + '\n');

// The island shortcode builds one source string, so emit a self-contained module.
const geometry = readFileSync(`${folder}/plot.mjs`, 'utf8').replace(/^export /gm, '');
const runtime = readFileSync(`${folder}/runtime.mjs`, 'utf8');
writeFileSync(`${folder}/index.js`, '// Generated by generate.mjs. Edit plot.mjs or runtime.mjs instead.\nconst series = ' + JSON.stringify(series) + ';\n' + geometry + '\n' + runtime);
