// Generated by generate.mjs. Edit plot.mjs or runtime.mjs instead.
const series = [{"name":"SciFact","color":"#dc244c","values":[0.016245,0.03115,0.028209,0.029876,0.032718]},{"name":"ArguAna","color":"#6047ff","values":[0.006772,0.01735,0.010199,0.000613,-0.001043]},{"name":"WANDS","color":"#009688","values":[-0.033478,-0.009709,-0.00827,-0.00897,-0.007916]},{"name":"CodeSearchNet","color":"#03a9f4","values":[0.046975,0.086092,0.107161,0.129529,0.135025]},{"name":"DBPedia-entity","color":"#ff9800","values":[0.032788,0.096173,0.111213,0.113639,0.114618]}];
// The same drawing renders the island and its self-contained static fallback.
const counts = [10, 25, 50, 100, 200];
const height = 300;
const format = value => `${value >= 0 ? '+' : ''}${value.toFixed(6)}`;
function drawing(series, width = 760, legend = false) {
  const left = 54, right = width - 20, top = 42, bottom = 246;
  // Preserve the original logarithmic candidate axis and shared gain range.
  const x = count => left + Math.log(count / 10) / Math.log(20) * (right - left);
  const y = value => bottom - (value + 0.05) / 0.2 * (bottom - top);
  let body = `<rect width="${width}" height="${height}" fill="var(--qi-surface,#f0f3fa)"/>`;
  body += `<text x="${left}" y="20" font-size="14" fill="var(--qi-fg,#303547)">nDCG@10 change over tuned fusion</text>`;
  for (const tick of [-0.05, 0, 0.05, 0.1, 0.15]) {
    body += `<line x1="${left}" y1="${y(tick)}" x2="${right}" y2="${y(tick)}" stroke="${tick === 0 ? 'var(--qi-muted,#656b7f)' : 'var(--qi-line,#abb1c7)'}" ${tick === 0 ? 'stroke-dasharray="5 4" stroke-width="2"' : 'stroke-width="1"'}/><text x="${left - 8}" y="${y(tick) + 5}" text-anchor="end" font-size="13" fill="var(--qi-muted,#656b7f)">${tick.toFixed(2)}</text>`;
  }
  for (const count of counts) body += `<text x="${x(count)}" y="267" text-anchor="middle" font-size="13" fill="var(--qi-fg,#303547)">${count}</text>`;
  body += `<text x="${(left + right) / 2}" y="292" text-anchor="middle" font-size="14" fill="var(--qi-muted,#656b7f)">Candidate count (log scale)</text>`;
  series.forEach((s, i) => {
    body += `<g data-series="${i}" style="color:${s.color}"><path class="rg-outline" d="${s.values.map((v, j) => `${j ? 'L' : 'M'}${x(counts[j])},${y(v)}`).join(' ')}" stroke="var(--qi-fg,#303547)" stroke-width="4" fill="none"/><path class="rg-line" d="${s.values.map((v, j) => `${j ? 'L' : 'M'}${x(counts[j])},${y(v)}`).join(' ')}" stroke="currentColor" stroke-width="2.5" fill="none"/>`;
    s.values.forEach((v, j) => {
      body += `<circle class="rg-point" cx="${x(counts[j])}" cy="${y(v)}" r="3.5" fill="currentColor"/>`;
      body += `<circle data-point="${j}" cx="${x(counts[j])}" cy="${y(v)}" r="10" fill="transparent" tabindex="0" role="button" aria-label="${s.name}, ${counts[j]} candidates, change ${format(v)}"><title>${s.name}: ${format(v)} at ${counts[j]} candidates</title></circle>`;
    });
    body += '</g>';
  });
  if (legend) {
    body += '<rect x="0" y="300" width="760" height="72" fill="#f0f3fa"/>';
    series.forEach((s, i) => {
      const lx = 24 + (i % 3) * 250, ly = 325 + Math.floor(i / 3) * 28;
      body += `<line x1="${lx}" y1="${ly - 5}" x2="${lx + 24}" y2="${ly - 5}" stroke="${s.color}" stroke-width="3"/><text x="${lx + 32}" y="${ly}" fill="#303547" font-size="14">${s.name}</text>`;
    });
  }
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${legend ? 372 : height}" class="qi-svg" font-family="'Mona Sans',Arial,sans-serif" role="img" aria-label="Best reranker gain over tuned fusion by candidate count">${body}</svg>`;
}

export function mount(node) {
  node.classList.add('rg');
  node.innerHTML = `<div class="qi-controls" role="group" aria-label="Highlight a dataset">${series.map((s,i) => `<button class="qi-chip" data-select="${i}" aria-pressed="false"><span class="qi-chip__swatch" style="background:${s.color}"></span>${s.name}</button>`).join('')}<button class="qi-chip" data-reset>Show all</button></div><div class="rg-plot"></div><p class="qi-status" role="status" aria-live="polite"></p>`;
  const plot = node.querySelector('.rg-plot');
  const status = node.querySelector('.qi-status');
  const buttons = Array.from(node.querySelectorAll('[data-select]'));
  let selected = null;
  function update(active = selected, point = null) {
    plot.querySelectorAll('[data-series]').forEach(group => {
      group.classList.toggle('rg-active', Number(group.dataset.series) === active);
    });
    buttons.forEach((button,i) => button.setAttribute('aria-pressed', String(i === selected)));
    if (active === null) status.textContent = 'Hover a line or select a dataset. Zero is the tuned-fusion baseline.';
    else {
      const s = series[active];
      status.textContent = point === null
        ? `${s.name}: ${format(s.values.at(-1))} nDCG@10 change at 200 candidates.`
        : `${s.name}: ${format(s.values[point])} nDCG@10 change at ${counts[point]} candidates.`;
    }
  }
  buttons.forEach((button,i) => {
    button.addEventListener('click', () => {selected = selected === i ? null : i; update();});
    button.addEventListener('pointerenter', () => update(i));
    button.addEventListener('pointerleave', () => update());
    button.addEventListener('focus', () => update(i));
    button.addEventListener('blur', () => update());
  });
  node.querySelector('[data-reset]').addEventListener('click', () => {selected = null; update();});
  function render() {
    // Drawing at the actual column width keeps labels readable on phones.
    plot.innerHTML = drawing(series, Math.max(280, Math.min(760, Math.round(plot.clientWidth))));
    plot.querySelectorAll('[data-series]').forEach(group => {
      const index = Number(group.dataset.series);
      group.addEventListener('pointerenter', () => update(index));
      group.addEventListener('pointerleave', () => update());
      group.querySelectorAll('[data-point]').forEach(point => {
        const countIndex = Number(point.dataset.point);
        const show = () => update(index, countIndex);
        point.addEventListener('pointerenter', show);
        point.addEventListener('focus', show);
        point.addEventListener('blur', () => update());
        point.addEventListener('click', () => {selected = index; show();});
        point.addEventListener('keydown', event => {
          if (event.key === 'Enter' || event.key === ' ') {event.preventDefault(); selected = index; show();}
        });
      });
    });
    update();
  }
  render();
  let lastWidth = plot.clientWidth;
  new ResizeObserver(() => {
    if (plot.clientWidth !== lastWidth) {lastWidth = plot.clientWidth; render();}
  }).observe(plot);
  node.dispatchEvent(new CustomEvent('island:ready', {bubbles:true}));
}
