name: Links

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@16361eb4acea8698b220b76c0d4e84e1fd22c61d # v2.6.0
        with:
          hugo-version: "0.123.0"
      - name: Install npm
        uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2.5.2
        with:
          node-version: '20'
      - name: Run hugo
        run: |
          bash -x ./install-and-build.sh
          CURRENT_DIR=$(pwd)
          export PATH="${CURRENT_DIR}/dart-sass:${PATH}"
          cd qdrant-landing && hugo --gc -b 'http://localhost:1314' && hugo serve --port 1314 &
          sleep 5 # wait for server to start
      - name: Internal Links Check
        id: lychee
        uses: lycheeverse/lychee-action@ec3ed119d4f44ad2673a7232460dc7dff59d2421 # v1.8.0
        with:
          args: --max-redirects 0 --exclude '.*' --include '^http://localhost:1314/[^%]+$' --base http://localhost:1314/ qdrant-landing/public/
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
