name: Update Github Stars

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 17 * * 0"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Run github-stars update script
        run: |
          bash -x automation/update-stats.sh
      - uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
        with:
          commit_message: "Update GitHub Stars"
          commit_user_name: "GitHub Actions"
          commit_user_email: "team@qdrant.com"