name: Update Github Stars

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 17 * * 0"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run github-stars update script
        run: |
          bash -x automation/update-github-stars.sh
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update GitHub Stars"
          commit_user_name: "GitHub Actions"
          commit_user_email: "team@qdrant.com"